app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  bot-settings:
    default-base-url: http://localhost:8090/bot

spring:
  application:
    name: scrapper

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
