app:
  scheduler:
    enable: true
    interval: 15s
    force-check-delay: 10s
    fetch-limit: 2
  bot-settings:
    default-base-url: http://localhost:8090/bot
  stack-over-flow-settings:
    default-base-url: https://api.stackexchange.com/2.3/
  git-hub-settings:
    default-base-url: https://api.github.com/
  database-access-type: jdbc
  client-retry-settings:
    backoff-type: linear
    attempts-limit: 3
    attempt-delay: 2s
    attempt-delay-limit: 60s
    retry-codes:
      - 500
      - 502
      - 503
      - 504
  api-rate-limit-settings:
    limit: 50
    refill-limit: 5
    refill-delay: 30s

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
