app:
  scheduler:
    enable: true
    interval: 15s
    force-check-delay: 10s
  stack-over-flow-settings:
    default-base-url: https://api.stackexchange.com/2.3/
  git-hub-settings:
    default-base-url: https://api.github.com/
  bot-settings:
    default-base-url: http://localhost:8090/bot

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://postgresql:5432/scrapper
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
