app:
  telegram-token: unset

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

springdoc:
  api-docs:
    path: /bot/api-docs
  swagger-ui:
    path: /bot/swagger-ui.html
  show-actuator: true
  use-management-port: true
  management:
    server:
      port: 8080
    endpoints:
      web:
        exposure:
          include:
            - openapi
            - swagger-ui

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
