app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-settings:
    default-base-url: http://localhost:8080/scrapper
  client-retry-settings:
    backoff-type: linear
    attempts-limit: 3
    attempt-delay: 2s
    attempt-delay-limit: 60s
    retry-codes:
      - 500
      - 502
      - 503
      - 504
  api-rate-limit-settings:
    limit: 50
    refill-limit: 5
    refill-delay: 30s
  kafka-settings:
    bootstrap-server: localhost:9092
    link-update-topic:
      name: link_updates
      consumer-group-id: link_updates_group
      auto-offset-reset: earliest

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
