/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Chat;
import edu.java.scrapper.domain.jooq.tables.Chatidlinkid;
import edu.java.scrapper.domain.jooq.tables.Link;
import edu.java.scrapper.domain.jooq.tables.records.ChatRecord;
import edu.java.scrapper.domain.jooq.tables.records.ChatidlinkidRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.18.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[]{Chat.CHAT.ID}, true);
    public static final UniqueKey<ChatidlinkidRecord> CONSTRAINT_C32 = Internal.createUniqueKey(Chatidlinkid.CHATIDLINKID, DSL.name("CONSTRAINT_C32"), new TableField[]{Chatidlinkid.CHATIDLINKID.CHAT_ID, Chatidlinkid.CHATIDLINKID.LINK_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[]{Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[]{Link.LINK.URL}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatidlinkidRecord, ChatRecord> CONSTRAINT_C = Internal.createForeignKey(Chatidlinkid.CHATIDLINKID, DSL.name("CONSTRAINT_C"), new TableField[]{Chatidlinkid.CHATIDLINKID.CHAT_ID}, Keys.CONSTRAINT_1, new TableField[]{Chat.CHAT.ID}, true);
    public static final ForeignKey<ChatidlinkidRecord, LinkRecord> CONSTRAINT_C3 = Internal.createForeignKey(Chatidlinkid.CHATIDLINKID, DSL.name("CONSTRAINT_C3"), new TableField[]{Chatidlinkid.CHATIDLINKID.LINK_ID}, Keys.CONSTRAINT_2, new TableField[]{Link.LINK.ID}, true);
}
